from .fixtures_surface_v00_square import surface_pairs as surface_pairs_v00_square
from .fixtures_surface_v00_square import surface_marker_aggregate_pairs as surface_marker_aggregate_pairs_v00_square

from .fixtures_surface_v01_apriltag import surface_pairs as surface_pairs_v01_apriltag
from .fixtures_surface_v01_apriltag import surface_marker_aggregate_pairs as surface_marker_aggregate_pairs_v01_apriltag

from .fixtures_surface_v01_square import surface_pairs as surface_pairs_v01_square
from .fixtures_surface_v01_square import surface_marker_aggregate_pairs as surface_marker_aggregate_pairs_v01_square
