"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['../pupil_src/capture/build_test.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
            'includes': 'cv2'
            }
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
